# Generated by Django 5.2.5 on 2025-08-20 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_image",
        ),
        migrations.AddField(
            model_name="event",
            name="event_status",
            field=models.CharField(
                choices=[("ongoing", "진행중"), ("finished", "종료"), ("on_hold", "보류중"), ("scheduled", "예정")],
                default="ongoing",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("reward_event", "리워드 이벤트"),
                    ("izakaya_event", "이자카야 이벤트"),
                    ("popular_izakaya_event", "인기이자카야 이벤트"),
                    ("season_limited", "시즌한정판"),
                ],
                default="reward_event",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_image", models.ImageField(blank=True, null=True, upload_to="events/")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="event_image", to="events.event"
                    ),
                ),
            ],
        ),
    ]
