# Generated by Django 5.2.4 on 2025-08-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("type", models.CharField(max_length=100)),
                ("member", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_wait_member", models.IntegerField()),
                ("schedule", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(choices=[("male", "Male"), ("female", "Female"), ("all", "All")], max_length=6),
                ),
                ("is_live", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("recruiting", "Recruiting"), ("in_progress", "In Progress")], max_length=20
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="category.category"),
                ),
            ],
        ),
    ]
