# Generated by Django 5.2.5 on 2025-08-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("final_goal", models.TextField()),
                ("common_mission", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("type", models.CharField(max_length=100)),
                ("member", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("max_wait_member", models.IntegerField()),
                ("schedule", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(choices=[("male", "Male"), ("female", "Female"), ("all", "All")], max_length=6),
                ),
                ("is_live", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("recruiting", "Recruiting"), ("in_progress", "In Progress")], max_length=20
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "왕초보"),
                            ("novice", "초보"),
                            ("intermediate", "중급"),
                            ("advanced", "고급"),
                            ("master", "마스터"),
                            ("any", "무관"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_permitted", models.BooleanField(default=False)),
                ("role", models.CharField(choices=[("MASTER", "방장"), ("MEMBER", "일반 회원")], max_length=50)),
            ],
        ),
    ]
