# Generated by Django 5.2.5 on 2025-08-18 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymission",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="study",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="category.category"),
        ),
        migrations.AddField(
            model_name="study",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="led_studies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="leadermission",
            name="study",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study"),
        ),
        migrations.AddField(
            model_name="dailymission",
            name="study",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study"),
        ),
        migrations.AddField(
            model_name="studymember",
            name="study",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study"),
        ),
        migrations.AddField(
            model_name="studymember",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
