# Generated by Django 5.2.4 on 2025-08-05 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="studies", to="category.category"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="gender",
            field=models.CharField(choices=[("any", "Any"), ("male", "Male"), ("female", "Female")], max_length=10),
        ),
        migrations.AlterField(
            model_name="study",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="led_studies", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="level",
            field=models.CharField(
                choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="member",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="study",
            name="status",
            field=models.CharField(
                choices=[("recruiting", "Recruiting"), ("in_progress", "In Progress")],
                default="recruiting",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="study",
            name="type",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline"), ("hybrid", "Hybrid")], max_length=20
            ),
        ),
    ]
