# Generated by Django 5.2.4 on 2025-08-14 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("final_goal", models.TextField()),
                ("common_mission", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study")),
            ],
        ),
        migrations.CreateModel(
            name="StudyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_permitted", models.BooleanField(default=False)),
                ("role", models.CharField(max_length=50)),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
