# Generated by Django 5.2.5 on 2025-08-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studymember",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
