# Generated by Django 5.2.5 on 2025-08-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_studymember_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="thumbnail_url",
            field=models.ImageField(blank=True, null=True, upload_to="studies/"),
        ),
    ]
