# Generated by Django 5.2.4 on 2025-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_dailymission_leadermission_studymember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studymember",
            name="role",
            field=models.CharField(choices=[("MASTER", "방장"), ("MEMBER", "일반 회원")], max_length=50),
        ),
    ]
