# Generated by Django 5.2.4 on 2025-08-14 02:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("studies", "0003_studyroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studyroom",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="studyroom",
            name="max_members",
        ),
        migrations.RemoveField(
            model_name="studyroom",
            name="owner",
        ),
        migrations.AddField(
            model_name="studyroom",
            name="category",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="category.category"),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("all", "All")], default="all", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="level",
            field=models.CharField(default="초급", max_length=50),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="max_wait_member",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="schedule",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="status",
            field=models.CharField(
                choices=[("recruiting", "Recruiting"), ("in_progress", "In Progress"), ("finished", "Finished")],
                default="recruiting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="type",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline"), ("mixed", "Mixed")],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studyroom",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studyroom",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="studyroom",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="StudyMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("MASTER", "방장"), ("MEMBER", "일반 회원")], default="MEMBER", max_length=10
                    ),
                ),
                ("is_permitted", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("study_room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.studyroom")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "study_room")},
            },
        ),
        migrations.DeleteModel(
            name="Study",
        ),
    ]
