# Generated by Django 5.2.5 on 2025-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_studyfavorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyfavorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
