events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 용량 추가
    client_max_body_size 30M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_vary on;

    upstream django_server {
        server django:8000;
    }

    # http
    server {
        listen 80;
        server_name api.ozcoding.site;

        # 추후 certbot ssl 인증서 갱신 시 필요
        location /.well-known/acme-challenge/ {
           root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # https
    server {
        server_name api.ozcoding.site;

        listen 443 ssl;

        ssl_certificate /etc/letsencrypt/live/api.ozcoding.site/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.ozcoding.site/privkey.pem;

        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        location /api/ {
            proxy_pass http://django_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
        }

        # WebSocket 프록시 추가
        location /ws/ {
            proxy_pass http://django_server;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_read_timeout 86400;
        }
    }
}
