events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 10M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_proxied any;
    gzip_vary on;

    upstream django_server {
        server django:8000;
    }

    server {
        listen 80;
        server_name storbit.o-r.kr;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name storbit.o-r.kr;

        ssl_certificate /etc/letsencrypt/live/storbit.o-r.kr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/storbit.o-r.kr/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/storbit.o-r.kr/chain.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://django_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_buffering off;
        }

        location /static/ {
            alias /storbit/staticfiles/;
            autoindex off;
            expires 1d;
            access_log off;
        }

        location /media/ {
            alias /storbit/media/;
            autoindex off;
            expires 1d;
            access_log off;
        }

        location /ws/ {
            proxy_pass http://django_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
