# Generated by Django 5.2.4 on 2025-08-06 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("fullname", models.CharField(max_length=100, verbose_name="성명")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="이메일")),
                ("nickname", models.CharField(max_length=50, unique=True, verbose_name="닉네임")),
                ("phone_number", models.CharField(blank=True, max_length=20, verbose_name="전화번호")),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("M", "남성"), ("F", "여성")], max_length=1, verbose_name="성별"
                    ),
                ),
                ("profile_image", models.URLField(blank=True, verbose_name="프로필 이미지")),
                ("goal", models.TextField(blank=True, verbose_name="목표")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성 상태")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 권한")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자들",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(default="KAKAO", max_length=20, verbose_name="제공자")),
                ("provider_id", models.CharField(max_length=255, unique=True, verbose_name="카카오 ID")),
                ("profile_image", models.URLField(blank=True, verbose_name="프로필 이미지")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "카카오 계정",
                "verbose_name_plural": "카카오 계정들",
                "db_table": "social_accounts",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(max_length=255, verbose_name="탈퇴 사유")),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                ("password", models.CharField(max_length=255, verbose_name="확인 비밀번호")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="탈퇴 신청일")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "회원 탈퇴",
                "verbose_name_plural": "회원 탈퇴들",
                "db_table": "withdrawal",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["nickname"], name="users_nicknam_172a64_idx"),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(fields=["user"], name="social_acco_user_id_588a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="socialaccount",
            index=models.Index(fields=["provider_id"], name="social_acco_provide_a20548_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["user"], name="withdrawal_user_id_138fd6_idx"),
        ),
        migrations.AddIndex(
            model_name="withdrawal",
            index=models.Index(fields=["created_at"], name="withdrawal_created_82f4a4_idx"),
        ),
    ]
