# Generated by Django 5.2.4 on 2025-08-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="프로필 이미지"),
        ),
    ]
