# Generated by Django 5.2.5 on 2025-08-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, verbose_name="프로필 이미지"),
        ),
    ]
