# Generated by Django 5.2.5 on 2025-08-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="study",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.study"),
        ),
    ]
