name: Code Quality Checks

on:
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up uv with Python 3.13
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.13"

      - name: Cache dependencies
        id: cache-uv
        uses: actions/cache@v3
        with:
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          path: ~/.cache/uv

      - name: Install dependencies
        run: uv sync --locked

      - name: Run isort
        run: uv run isort . --check --diff

      - name: Run black
        run: uv run black . --check

      - name: Set multiline environment variable
        run: |
          mkdir envs
          echo "${{ secrets.DJANGO_ENVS }}" >> envs/.local.env

      - name: Run Mypy
        run: uv run mypy .

  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pw1234
          POSTGRES_DB: storbit
          TZ: Asia/Seoul
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up uv with Python 3.13
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.13"

      - name: Cache dependencies
        id: cache-uv
        uses: actions/cache@v3
        with:
          key: uv-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'uv.lock') }}
          path: ~/.cache/uv

      - name: Install dependencies
        run: uv sync --locked

      - name: Set multiline environment variable
        run: |
          mkdir envs
          echo "${{ secrets.DJANGO_ENVS }}" >> envs/.local.env

      - name: Run Django Migration
        run: uv run python manage.py migrate

      - name: Check each app has test & Run coverage
        run: |
          ran_tests=false
          apps="category studies"

          for app_name in $apps; do
            app_path="apps/$app_name"
            if [ -d "$app_path" ]; then
              test_files=$(find "$app_path" -type f \( -name "tests.py" -o -name "test_*.py" \))
              if [ -n "$test_files" ] && grep -q "def test_" $test_files 2>/dev/null; then
                echo "✅ Running tests for $app_name"
                uv run coverage run --source="$app_path" --append manage.py test "apps.$app_name"
                ran_tests=true
              else
                echo "⚠️  No test functions found in $app_name"
              fi
            else
              echo "⛔️ Directory not found for $app_name"
            fi
          done

          if [ "$ran_tests" = true ]; then
            uv run coverage report -m
          else
            echo "🚫 No tests were run. Skipping coverage report."
          fi
